---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tk-system-traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tk-system-traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    namespace: tk-system
    name: traefik-ingress-controller
