---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tk-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          imagePullPolicy: IfNotPresent
          args:
            - --api.insecure
            - --log.level=INFO
            - --log.filePath=/var/log/traefik/traefik.log
            - --accesslog
            - --accesslog.filePath=/var/log/traefik/access.log
            - --ping
            - --providers.kubernetescrd
            - --entrypoints.web.address=:8008
            - --entrypoints.web.forwardedheaders.insecure
            # - --entrypoints.websecure.address=:4443
            # - --entrypoints.tcpep.address=:8000
            # - --entrypoints.udpep.address=:9000/udp
            # - --certificatesresolvers.default.acme.tlschallenge
            # - --certificatesresolvers.default.acme.email=foo@you.com
            # - --certificatesresolvers.default.acme.storage=acme.json
            # # Please note that this is the staging Let's Encrypt server.
            # # Once you get things working, you should remove that whole line altogether.
            # - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 8008
            - name: admin
              containerPort: 8080
            # - name: websecure
            #   containerPort: 4443
            # - name: tcpep
            #   containerPort: 8000
            # - name: udpep
            #   containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: 150m
              memory: 400Mi
            requests:
              cpu: 150m
              memory: 400Mi
          volumeMounts:
            - name: container-log
              mountPath: /var/log/traefik
        - name: node-exporter
          image: prom/node-exporter:v0.18.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9100
          readinessProbe:
            httpGet:
              path: /
              port: 9100
          livenessProbe:
            httpGet:
              path: /
              port: 9100
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 30m
              memory: 30Mi
        - name: fluent-bit
          image: fluent/fluent-bit:1.4
          # image: grafana/fluent-bit-plugin-loki:1.5.0-amd64
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fluent-bit-config
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 30m
              memory: 30Mi
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/append_tag.lua
              subPath: append_tag.lua
            - name: container-log
              mountPath: /var/log/container
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: container-log
          emptyDir: {}
