---
apiVersion: v1
kind: Service
metadata:
  namespace: tk-system
  name: traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8008
    - protocol: TCP
      name: admin
      port: 8080
    # - protocol: TCP
    #   name: websecure
    #   port: 4443
    # - protocol: TCP
    #   name: tcpep
    #   port: 8000
    # - protocol: UDP
    #   name: udpep
    #   port: 9000
    - protocol: TCP
      name: node-exporter
      port: 9100
  selector:
    app: traefik
