---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - namespace.yml
  - ingressroute.yml
namespace: xx-system
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: fluent-bit-config
    namespace: tk-system
    behavior: merge
    envs:
      - envs/fluent-bit-configmap.env.example
  - name: fluentd-config
    namespace: tk-system
    behavior: merge
    envs:
      - envs/fluentd-configmap.env.example
  - name: grafana-config
    namespace: tk-system
    behavior: merge
    envs:
      - envs/grafana-configmap.env.example
  - name: loki-config
    namespace: tk-system
    behavior: merge
    envs:
      - envs/loki-configmap.env.example
  - name: prometheus-config
    namespace: tk-system
    behavior: merge
    envs:
      - envs/prometheus-configmap.env.example
secretGenerator:
  - name: aws-secret
    namespace: tk-system
    behavior: merge
    envs:
      - envs/aws-secret.env.example
