---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: tk-system
data:
  fluent.conf: |
    <source>
      @type forward
      @label @FORWARD
      port 24224
      bind 0.0.0.0
    </source>

    <label @FORWARD>
      <filter **>
        @type record_transformer
        enable_ruby true
        <record>
          tag ${tag}
          time ${time.strftime('%Y-%m-%dT%H:%M:%S.%NZ')}
        </record>
      </filter>
      <match **>
        @type copy
        <store>
          @type stdout
        </store>
        <store>
          @type loki
          url "#{ENV['LOKI_URL']}"
          extra_labels {"job":"fluentd"}
          flush_interval 10s
          flush_at_shutdown true
          buffer_chunk_limit 1m
          <label>
            tag
          </label>
        </store>
        <store>
          @type s3
          @id out_s3
          @log_level info
          aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"
          aws_sec_key "#{ENV['AWS_SECRET_ACCESS_KEY']}"
          s3_bucket "#{ENV['S3_BUCKET_NAME']}"
          s3_region "#{ENV['S3_BUCKET_REGION']}"
          s3_object_key_format "#{ENV['S3_OBJECT_KEY_PREFIX']}%Y/%m/%d/${tag}-%H-%M-%S-%{index}.%{file_extension}"
          <buffer tag,time>
            @type file
            path /fluentd/log/buffers/s3
            timekey 3600
            timekey_wait 60
            timekey_use_utc true
            chunk_limit_size 256m
          </buffer>
        </store>
      </match>
    </label>
