---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tk-system
  name: fluentd
  labels:
    app: fluentd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: twihike/fluentd:v0.1.0
          envFrom:
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: fluentd-config
          ports:
            - name: forward
              containerPort: 24224
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 400Mi
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
        - name: node-exporter
          image: prom/node-exporter:v0.18.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9100
          readinessProbe:
            httpGet:
              path: /
              port: 9100
          livenessProbe:
            httpGet:
              path: /
              port: 9100
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 30m
              memory: 30Mi
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
