---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tk-system-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tk-system-prometheus
subjects:
  - kind: ServiceAccount
    namespace: tk-system
    name: prometheus
